// Code generated by htgo-gen-loaders. DO NOT EDIT.
// Generated for handlers in ./app/pages/

package pages

import (
	"github.com/bertilxi/htgo"
	api "github.com/bertilxi/htgo/examples/sink/app/pages/api"
)

// LoaderRegistry maps page routes to their corresponding loader functions.
// Loaders return (any, error) and their data is used as props for SSR.
var LoaderRegistry = map[string]htgo.PageLoader{
	"/": LoadIndex,
	"/about": LoadAbout,
}

// HandlerRegistry maps API routes to their corresponding handler functions.
// Handlers have full Gin API control - use c.JSON(), c.File(), etc. directly.
var HandlerRegistry = map[string]htgo.Handler{
	"/api/data": api.Data,
	"/api/health": api.Health,
}
