// Code generated by htgo. DO NOT EDIT.
// This file is auto-generated from .go files colocated with pages.
// If this file doesn't exist, run: go generate ./app/pages

package pages

import (
	"github.com/gin-gonic/gin"
)

// LoaderRegistry maps routes to their corresponding loader functions.
// This is auto-generated from .go files colocated with pages.
var LoaderRegistry = map[string]func(c *gin.Context) (any, error){
	"/": LoadIndex,
	"/about": LoadAbout,
}
