// Code generated by htgo-gen-loaders. DO NOT EDIT.
// Generated for handlers in ./app/pages/

package pages

import (
	"github.com/bertilxi/htgo"
	api "github.com/bertilxi/htgo/examples/sink/app/pages/api"
)

// HandlerRegistry maps routes to their corresponding handler functions.
// This is auto-generated from .go files colocated with pages and in pages/api/.
// Page loaders provide props for SSR, while API handlers return any response type.
var HandlerRegistry = map[string]htgo.Handler{
	"/": LoadIndex,
	"/about": LoadAbout,
	"/api/data": api.Data,
	"/api/health": api.Health,
}
